Fix/collision component
n0bis/Warcell pull request #19
Opened 2020-05-04 09:35 UTC by prikx

2020-05-04 09:57 UTC, n0bis requested changes

2020-05-04 09:57 UTC, n0bis commented on Warcell/OSGiCollision/src/main/java/warcell/osgicollision/Activator.java
> +public class Activator implements BundleActivator {
Denne skal vel ikke bruges?

2020-05-04 09:57 UTC, n0bis commented on Warcell/OSGiCommon/src/main/java/warcell/common/data/entityparts/CollisionPart.java
> +    public void process(GameData gameData, Entity entity) {
Denne kunne vel være empty?

2020-05-04 10:25 UTC, prikx commented on Warcell/OSGiCollision/src/main/java/warcell/osgicollision/Activator.java
> +public class Activator implements BundleActivator {
Yes we do

2020-05-04 10:31 UTC, Mathiask1 commented on Warcell/OSGiCollision/src/main/java/warcell/osgicollision/Activator.java
> +public class Activator implements BundleActivator {
fix pom fil

2020-05-04 10:32 UTC, prikx commented on Warcell/OSGiCollision/src/main/java/warcell/osgicollision/Activator.java
> +public class Activator implements BundleActivator {
no you

2020-05-05 13:36 UTC, n0bis approved these changes

2020-05-05 13:37 UTC, merged